### ISSUE TITLE
Plugin won't enable 

### ISSUE THREAD

**Issue by XMrCatX** [Xquiset/SetHomes#11]
Hi,

I just updated your plugin to the latest version in the hopes to be able to use it in 1.6.3 but for some reason, it keeps giving an error when enabling.
`[10:09:58] [Server thread/ERROR]: Error occurred while enabling SetHomes v1.2.9 (Is it up to date?)
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_265]
	at com.samleighton.xquiset.sethomes.SetHomes.getMaxHomes(SetHomes.java:266) ~[?:?]
	at com.samleighton.xquiset.sethomes.commands.SetHome.<init>(SetHome.java:27) ~[?:?]
	at com.samleighton.xquiset.sethomes.SetHomes.registerCommands(SetHomes.java:157) ~[?:?]
	at com.samleighton.xquiset.sethomes.SetHomes.onEnable(SetHomes.java:59) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-216]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-216]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-216]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-216]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-216]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-216]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-216]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[10:09:58] [Server thread/INFO]: [SetHomes] Disabling SetHomes v1.2.9
`
In the picture are the other plugins that I use and the log.
[log.txt](https://github.com/Xquiset/SetHomes/files/5358795/log.txt)
![WinSCP_screen](https://user-images.githubusercontent.com/44335993/95652644-deb99600-0af2-11eb-815e-12a11a2df6f2.png)

**Comment by Xquiset** [comment]
Hello,

It looks like it failed when looking for a value in the config, and it could not find it. The error message indicates that there was an issue with the max-homes setting. Could you send what your config.yml looks like?

Best Regards,
Xquiset

**Comment by XMrCatX** [comment]
Hi Xquiset,

My excuses for the late response, I noticed that the max homes were set to 0.
I never changed the config before but I changed it to 5 and now it starts without any problems.
Thx for the help and the great plugin!

Kind regards,
XMrCatX (aka Ward 😉)
