### ISSUE TITLE
Internal Error after player sets home named "."

### ISSUE THREAD

**Issue by SpechtD** [Xquiset/SetHomes#17]
After a player sets a home named "." the plugin completely stops working just for them. 

Here is the error in the console:
```[13:15:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'homes' in plugin SetHomes v1.2.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-259]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-259]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2005) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1816) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1769) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1135) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-259]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_265]
        at com.samleighton.xquiset.sethomes.SetHomes.getHomeLocaleFromConfig(SetHomes.java:370) ~[?:?]
        at com.samleighton.xquiset.sethomes.SetHomes.getPlayersNamedHomes(SetHomes.java:231) ~[?:?]
        at com.samleighton.xquiset.sethomes.commands.ListHomes.listHomes(ListHomes.java:81) ~[?:?]
        at com.samleighton.xquiset.sethomes.commands.ListHomes.onCommand(ListHomes.java:54) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-259]
        ... 19 more
```

**Comment by SpechtD** [comment]
After reading through the code on GitHub, it seems like the last commit fixed the issue.

I just didn't have the latest version, because the file [here](https://dev.bukkit.org/projects/set-homes) hasn't been updated yet.

**Comment by Xquiset** [comment]
Hi,

I have been trying to upload the latest build of the plugin to Bukkit, but there have been delays with that process. My apologies. I will let you know here once the plugin gets approved for the general public. Also its really cool that you were able to find my little fix for this issue. I honestly didn't think anyone else looked at the code here besides me.

Best Regards,
Xquiset
