### ISSUE TITLE
An Internal Error

### ISSUE THREAD

**Issue by TheRealTangsten** [Xquiset/SetHomes#18]
I've been using this plugin for the past days and some of the players on my server, me included, have a problem setting their second home, namely I get an "An internal error has occoured while attempting to perform this command". Whenever I try to set a named home I get the following error:
```
[18:18:57 ERROR]: Unhandled exception executing command 'sethome' in plugin SetHomes v1.2.9
org.bukkit.command.CommandException: Unhandled exception executing command 'sethome' in plugin SetHomes v1.2.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-294]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:581) ~[?:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:570) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2008) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1819) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1772) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-294]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayerGroups(Permission_SuperPerms.java:91) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:637) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:649) ~[?:?]
        at com.samleighton.xquiset.sethomes.commands.SetHome.getMaxHomesAllowed(SetHome.java:132) ~[?:?]
        at com.samleighton.xquiset.sethomes.commands.SetHome.onCommand(SetHome.java:67) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-294]
        ... 22 more
```
It's a 1.16.4 Paper-294 server.  Attached are my homes.yml and config.yml
[Xhomes - Copy.txt](https://github.com/Xquiset/SetHomes/files/5725335/Xhomes.-.Copy.txt)
[Xconfig - Copy.txt](https://github.com/Xquiset/SetHomes/files/5725337/Xconfig.-.Copy.txt)

**Comment by Xquiset** [comment]
Hello,

I am sorry you're having issues with the plugin. Could you please tell me what permissions plugin(s) you're using? It seems like its tried to use Vault to connect with a permissions plugin, but the Permissions plugin does not have groups enabled.

Best Regards,
Xquiset

**Comment by TheRealTangsten** [comment]
Thank you for your hasty response.

I am using the plugin "PowerRanks"

**Comment by Xquiset** [comment]
No problem,

I have checked the "Vault" page [here](https://dev.bukkit.org/projects/vault) and it does not list "PowerRanks" as a compatible permissions plugin. To fix this issue I believe you will need to uninstall Vault. This means you would lose the max-homes functionality. Another option would be to either switch to a Vault compatible permissions plugin which is listed on the page linked above, or use LuckPerms which is another permissions plugin that does not require Vault. The choice is yours really, but the issue here is definitely because you have Vault installed with an unsupported permissions plugin.

Hope this helps,
Xquiset

**Comment by TheRealTangsten** [comment]
Thank you for the answer!

I will look into other permission plugins and transition.
