### ISSUE TITLE
Error when running /home

### ISSUE THREAD

**Issue by VeryGoodDog** [Xquiset/SetHomes#4]
I don't really know what to put in an issue for this but when running /home I get this error:
```
[10:36:38] [Server thread/INFO]: VeryGoodDog issued server command: /home
[10:36:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'home' in plugin SetHomes v1.2.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: location.world
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:617) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:453) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	at com.samleighton.xquiset.sethomes.commands.GoHome.teleportHome(GoHome.java:158) ~[?:?]
	at com.samleighton.xquiset.sethomes.commands.GoHome.onCommand(GoHome.java:56) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[craftbukkit-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
	... 17 more
```
LMK if you need more info.

**Comment by Xquiset** [comment]
Hello,
Are you still encountering this error? I cannot reproduce this on my side.
Best Regards,
Xquiset
