### ISSUE TITLE
Internal error when trying to set multiple homes

### ISSUE THREAD

**Issue by RIPTIDE6969** [Xquiset/SetHomes#7]
If I try and set more that 1 home the server has an internal error. I have checked and have set the server rule to have 100 homes per player so that isn't the issue. This really breaks the plugin

**Comment by Xquiset** [comment]
Hi,
Could you please give me a list of the plug-ins you’re using, and a copy of the server console when the error occurs?
Best Regards,
Xquiset

**Comment by RIPTIDE6969** [comment]
I am using, CoreProtect v19, LockettePro, Multiverse-Core-4.1.0, SetHomes-1.2.7, Vault, ViaVersion-3.0.1

**Comment by RIPTIDE6969** [comment]
Here is the error I am getting

[17:27:16] [Server thread/INFO]: MR_SCROMBIE issued server command: /sethome avillage
[17:27:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sethome' in plugin SetHomes v1.2.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:755) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1703) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1546) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayerGroups(Permission_SuperPerms.java:91) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:637) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:649) ~[?:?]
        at com.samleighton.xquiset.sethomes.commands.SetHome.getMaxHomesAllowed(SetHome.java:109) ~[?:?]
        at com.samleighton.xquiset.sethomes.commands.SetHome.onCommand(SetHome.java:60) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Spigot2.jar:git-Spigot-0287a20-7560f5f]
        ... 18 more

**Comment by Xquiset** [comment]
Hello,

This issue should be fixed with the latest version of the SetHomes (V1.2.9). The download can be found here: [https://dev.bukkit.org/projects/set-homes/files/3075503/download](https://dev.bukkit.org/projects/set-homes/files/3075503/download)

Sorry for the delayed reply,
Xquiset
